development:
  adapter: postgresql
  encoding: unicode
  database: burnr_dev
  username: ashita
  password:
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: burnr_test
  username: ashita
  password:
  pool: 5
